### ISSUE TITLE
User Friendly Track Setup

### ISSUE THREAD

**Issue by thefishlive** [CodingBadgers/MineKart#1]
Track setup and deletion needs to me more user friendly

**Comment by samoatesgames** [comment]
## Deletion and course reset commands

Commands need to exist which can remove/reset parts of a course as well as command which can completely remove a course in its entirety.

Commands for removing all warp points (spawn, lobby, spectate, checkpoint) should exist. /mk delete[warpname] [coursename] [args...]

Commands for editing all warp points should exist. This will simply set the warp to the current location (or w/e selection) /mk edit[warpname] [coursename] [args...]

**Comment by thefishlive** [comment]
Course visualisation complete, doesn't actually change any blocks so crashes shouldn't be an issue
