### ISSUE TITLE
Signs not working 100% of the time

### ISSUE THREAD

**Issue by Hodgy** [CodingBadgers/MineKart#3]
The signs do join don't always work. Either need to reload plugin or break and replace the sign for it to work

**Comment by samoatesgames** [comment]
Hard to reproduce.
Suggested fix is to have a '/mk reload' command, which ends all active games and refreshes all signs.

**Comment by samoatesgames** [comment]
https://github.com/CodingBadgers/MineKart/commit/8a4e4027390e6991b3ad063bb4116ae02d87fe65
